In [24]:
class Character:
    def __init__(self):
        self.health=200
        
    def move(self):
        self.health-=10
        
    def rest(self):
        self.health+=10
    
    def checkHealth(self):
        print('Health :',self.health)

In [25]:
class Knight(Character):
    def move(self):
        self.health-=15
    def attack(self):
        print('공격합니다')

In [26]:
knight_1=Knight()
knight_1.checkHealth()

Health : 200


In [27]:
knight_1.move()
knight_1.checkHealth()

Health : 185


In [28]:
class Healer(Character):
    def __init__(self):
        super().__init__()
        self.mana=100
    def heal(character):
        self.mana-=10
        character.rest() 
    def checkMana(self):
        print("현재 mana: ",self.mana)
    

In [29]:
healer_1=Healer()

In [30]:
healer_1.checkMana()

현재 mana:  100


In [35]:
import numpy as np
x=np.array([[[1, 2, 3, 3], [2, 3, 4, 5], [1, 2, 3, 6]], [[1, 2, 3, 3], [2, 3, 4, 5], [1, 2, 3, 6]]])
x.shape


(2, 3, 4)

In [38]:
x = np.linspace(1, 20, 5)
x?


In [43]:
x=np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
print(x[1:3])

[1 2]


In [45]:
x=np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
print(x[1:3])   #2차원에서 2행 3행 출력

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [47]:
print(x[1:3,1:3])  #2행 3행중 2열,3열 출력

[[ 6  7]
 [11 12]]


In [48]:
print(x[1:3,1])   #차원수가 하나 줄어듦

[ 6 11]


In [49]:
print(x[1:3,1:2])

[[ 6]
 [11]]


In [50]:
x=np.arange(30).reshape(2,5,3)

In [51]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [53]:
print(x[:,3:5,1])


[[10 13]
 [25 28]]


In [54]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
print(a[1][1])

6


In [58]:
print(a[[1,1],[1,2]])

[6 7]


In [59]:
print(a[[1,1],[1,2]])

[6 7]


In [60]:
print(a>3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [61]:
print(a>10)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]


In [62]:
print(a[a>10])

[11 12 13 14 15 16 17 18 19]


In [63]:
print(a[a>4])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [64]:
print(a[a==10])

[10]


In [65]:
print(a[a==13])   #a에 13인 것을 출력 

[13]


In [66]:
print(a[~(a==1)])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [67]:
print(a[a!=1])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [68]:
print(a[a!=1])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [69]:
print(a[(a>3)&(a<8)])

[4 5 6 7]


In [70]:
print(a[a!=1])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [71]:
np.random.rand(5,5)   #shqpe 5,5

array([[0.22121018, 0.29327028, 0.75783637, 0.87062409, 0.52572112],
       [0.54512006, 0.79378297, 0.95489245, 0.3992027 , 0.58642286],
       [0.22067059, 0.50978374, 0.81703064, 0.43229048, 0.07678882],
       [0.96314451, 0.2867983 , 0.01946866, 0.12302702, 0.26456259],
       [0.59413146, 0.72795757, 0.1155628 , 0.33884561, 0.48617962]])

In [74]:
np.random.randint(1,10)    #1~9까지 정수 중 하나 출력

6

In [76]:
np.random.randint(1,10,size=(5,5))   

array([[4, 7, 5, 1, 4],
       [2, 5, 4, 5, 8],
       [2, 4, 9, 5, 7],
       [4, 1, 5, 2, 6],
       [7, 6, 8, 9, 3]])

In [77]:
np.random.randint(1,15, size=(4,5))

array([[ 9,  9, 11,  9,  8],
       [ 2,  5,  5, 11,  8],
       [ 1,  5,  3,  6, 14],
       [ 6,  5, 14,  8,  9]])

In [78]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [80]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
 x.ravel()    #행ㅌ.기준으로 펼치기   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [85]:
x.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
x.ravel(order='F')

array([ 0, 15,  3, 18,  6, 21,  9, 24, 12, 27,  1, 16,  4, 19,  7, 22, 10,
       25, 13, 28,  2, 17,  5, 20,  8, 23, 11, 26, 14, 29])

In [87]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
x=np.arange(1,4)
x

array([1, 2, 3])

In [95]:
y=np.arange(4,7)
y

array([4, 5, 6])

In [98]:
np.concatenate([x,y])   #행 기준으로 연결

array([1, 2, 3, 4, 5, 6])

In [100]:
x=np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
y=np.arange(10,20).reshape(2,5)
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [104]:
np.concatenate([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [105]:
np.concatenate([x,y],axis=1)   #열기준으로 연결

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [114]:
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
x=np.split(x,4)  #행을 기준으로 4개로 분리   -> 리스트로 분리
x
type(x)

list

In [116]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
np.split(x,2)    #2개의 리스트로 분리 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [120]:
np.split(x,2,axis=1) #열기준 2개의 리스트로 분리

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [127]:
x=np.arange(4).reshape(2,2)
y=np.arange(4).reshape(2,2)
print(x)
print(y)
x.dot(y)   #행렬곱

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


array([[ 2,  3],
       [ 6, 11]])

In [123]:
x=np.array([1,2,3])
x+1

array([2, 3, 4])

In [124]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(1,4)
x+y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [125]:
x=np.array([10,20,30]).reshape(3,1)
y=np.arange(1,4)
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [132]:
x=np.arange(9).reshape(3,3)
y=np.arange(6).reshape(3,2)
print(x)

print(y)
x.dot(y)   #행렬곱 x*y

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]


array([[10, 13],
       [28, 40],
       [46, 67]])

In [134]:
np.transpose(x)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [138]:
x=np.arange(9).reshape(3,3)
np.linalg.det(x)

0.0

In [139]:
np.mean(x)


4.0

In [140]:
np.median(x)

4.0

In [142]:
np.std(x)

2.581988897471611

In [143]:
a=np.array([1,3,10,4,5])
np.median(a)

4.0

In [144]:
np.var(x)

6.666666666666667

In [154]:
print(x,'\n')
print(np.sum(x))   #전체원소 더함
print(np.sum(x,axis=0))   #행기준으로 더함
np.sum(x,axis=1)   #열기준으로 더함



[[0 1 2]
 [3 4 5]
 [6 7 8]] 

36
[ 9 12 15]


array([ 3, 12, 21])

In [157]:
np.argmax(x)

8

In [159]:
np.argmin(x)

0

In [161]:

np.all(x>1)

False

In [162]:
np.any(x>1)

True

In [167]:
x=np.arange(9).reshape(3,3)
print(x)
np.where(x>4)   #1,2  2,0  2,1   2,2

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [164]:
np.where(x>4,x,-100    #4보다 크면 x값 그대로 아니면 -100 값으로 대체 

array([[-100, -100, -100],
       [-100, -100,    5],
       [   6,    7,    8]])

In [165]:
x=np.arange(4).reshape(2,2)
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [174]:
x=np.arange(1,10).reshape(3,3)
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
y=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
y

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [177]:
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [178]:
x*y    #??

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [179]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [187]:
x=np.linspace(1,20,30)+10
x

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [210]:
x=np.random.randint(1,100,size=(2,10,10))

In [211]:
x

array([[[83, 11, 90,  6, 60, 86, 20, 49, 23, 81],
        [37, 80, 28, 59, 31, 42, 80, 16, 72, 10],
        [28, 40, 36, 59, 31, 74, 47, 55, 26, 60],
        [48, 84, 51, 17, 41, 80, 38, 40, 49, 93],
        [28, 93, 87, 77, 33, 74, 75, 17, 10, 22],
        [54,  6, 55, 83, 78, 77, 78, 47, 17, 30],
        [94, 43, 67, 16, 78, 44, 31, 42, 80, 49],
        [37, 20, 45, 52, 66, 13, 65, 91, 41, 83],
        [78, 64, 37, 56, 44, 73, 46, 60, 32, 57],
        [79, 16,  5, 49, 13, 90, 54, 97,  1, 36]],

       [[66, 60, 70, 42, 51, 52, 92, 91, 61, 58],
        [53, 51, 59, 53, 46, 83, 69, 89, 76, 88],
        [73, 16, 59, 27, 69, 96, 69, 44, 76, 55],
        [47, 93, 11, 32, 34, 46, 90, 47, 46,  4],
        [46, 91, 13, 37, 92, 92,  4, 71, 71, 68],
        [84,  4, 47, 74, 82, 75, 13, 34, 44, 36],
        [27, 82, 30, 61, 85, 34, 87, 39, 97, 98],
        [12, 23, 82, 15, 55, 25,  2,  5, 31, 82],
        [73, 43, 35, 30, 65, 11, 20, 85, 45, 58],
        [ 8, 31, 96, 50, 18, 67, 16, 81, 67, 34]

In [212]:
x=np.where(x>=50,1,2)
x

array([[[1, 2, 1, 2, 1, 1, 2, 2, 2, 1],
        [2, 1, 2, 1, 2, 2, 1, 2, 1, 2],
        [2, 2, 2, 1, 2, 1, 2, 1, 2, 1],
        [2, 1, 1, 2, 2, 1, 2, 2, 2, 1],
        [2, 1, 1, 1, 2, 1, 1, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 1, 2, 2, 2],
        [1, 2, 1, 2, 1, 2, 2, 2, 1, 2],
        [2, 2, 2, 1, 1, 2, 1, 1, 2, 1],
        [1, 1, 2, 1, 2, 1, 2, 1, 2, 1],
        [1, 2, 2, 2, 2, 1, 1, 1, 2, 2]],

       [[1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 2, 1, 1, 1, 1, 1],
        [1, 2, 1, 2, 1, 1, 1, 2, 1, 1],
        [2, 1, 2, 2, 2, 2, 1, 2, 2, 2],
        [2, 1, 2, 2, 1, 1, 2, 1, 1, 1],
        [1, 2, 2, 1, 1, 1, 2, 2, 2, 2],
        [2, 1, 2, 1, 1, 2, 1, 2, 1, 1],
        [2, 2, 1, 2, 1, 2, 2, 2, 2, 1],
        [1, 2, 2, 2, 1, 2, 2, 1, 2, 1],
        [2, 2, 1, 1, 2, 1, 2, 1, 1, 2]]])

In [216]:
print(x[1:, 5:,5:])


[[[1 2 2 2 2]
  [2 1 2 1 1]
  [2 2 2 2 1]
  [2 2 1 2 1]
  [1 2 1 1 2]]]


In [219]:
import pandas as pd
x=[1,2,3,4,5]
a=pd.Series(x)
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [220]:
x=[1,2,3,4,5]
x=pd.Series(x)

print(x.index)
print(x.values)

RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [223]:
x={'수학':90,'영어':80,'과학':95,'미술':30}
x=pd.Series(x)
x

수학    90
영어    80
과학    95
미술    30
dtype: int64

In [224]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [225]:
x['미술']

30

In [228]:
x['영어':'미술']

영어    80
과학    95
미술    30
dtype: int64

In [231]:
y=pd.Series(x,index=['수학','영어','과학'])
y

수학    90
영어    80
과학    95
dtype: int64

In [232]:
student_1={"수학":90,"영어":80,"과학":30,"미술":60}
student_2={"수학":80,"영어":70,"과학":90,"미술":40}

In [233]:
index_1=['홍길동' for i in range(len(student_1))]+['이몽룡' for i in range(len(student_2))]
index_1

['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']

In [244]:
index_2=[i for i in student_1]+[i for i in student_2]
index_2

index_2=list(student_1.keys())+list(student_2.keys())
index_2

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [236]:
value_all=list(student_1.values())+list(student_2.values())
value_all

[90, 80, 30, 60, 80, 70, 90, 40]

In [239]:
students=pd.Series(value_all,index=[index_1,index_2])
students

홍길동  수학    90
     영어    80
     과학    30
     미술    60
이몽룡  수학    80
     영어    70
     과학    90
     미술    40
dtype: int64

In [242]:
students['홍길동']

수학    90
영어    80
과학    30
미술    60
dtype: int64

In [243]:
students['홍길동']['영어']

80