In [1]:
##choco=Dog()에서 choco는 객체 클래스는 설계도 self는 객체 , self는 객체와 관련
##인스턴스는 설계도를 바탕으로 소프트웨어 세계에 구현된 구체적인 실체
#객체는 설계도를 바탕으로 소프트웨어 세계에 구현된 구체적인 실체,설계도를 바탕으로 소프트웨어 세계에 구현된 구체적인 실체

In [108]:
class Dog:
    def __init__(self,name,color): #self는 인스턴스 즉 클래스 dog안의 객체를 인스턴스 
        self.hungry=0   #인스턴스 속성 값 0으로 초기화
        self.name=name   #인스턴스 name속성을 name으로 초기화 다른 인스턴스메서드에서 name사용가능
        self.color=color  #인스턴스 color 속성을 color로 초기화 다른 인스턴스메서드에서 color사용가능
        
    def eat(self): #인스턴스 매서드 -> 인스턴스로 접근
        self.hungry-= 10  
        print('eat',self.hungry)
    def walk(self):
        self.hungry+= 10
        print('walk',self.hungry)
    def showme(self):
        print(f"{self.name}:{self.color}")

In [110]:
class Dog:   #dog라는 클래스 정의
    def __init__(self,name,color): # self 인스턴스 정의 init함수라 무조건 실행
        self.hungry=0
        self.name=name
        self.color=color
    
    def eat(self):   #인스턴스의 함수
        self.hungry-=10
        print('밥먹음',self.hungry)
    
    def walk(self):
        self.hungry+=10
        print('산책',self.hungry)
    def showme(self):
        print(f"{self.name}:{self.color}")
        

In [113]:
choco=Dog('choco','black')   #클래스 객체화
choco.eat()
choco.eat()
choco.walk()
choco.showme()

밥먹음 -10
밥먹음 -20
산책 -10
choco:black


In [114]:
choco=Dog('choco','black')
choco.eat()
choco.eat()
choco.showme()

밥먹음 -10
밥먹음 -20
choco:black


In [36]:
jjong=Dog('dd','white')
jjong.walk()
jjong.showme()

walk 10
dd:white


In [49]:
class Dog:
    dog_count=0
    
    def __init__(self,name,color):
        self.name=name
        self.color=color
        self.dog_count=0
        Dog.dog_count+=1
        
    def dogCount(self):
        self.dog_count+=1
        print('총 강아지는',Dog.dog_count)
        print('내 강아지는',self.dog_count)

In [115]:
class Dog:
    dog_count=0
    
    def __init__(self,name,color):
        self.name=name
        self.color=color
        Dog.dog_count+=1
    
    def dogCount(self):
        self.dog_count+=1
        print('총강아지는 ', Dog.dog_count)
        print('내 강아지는 ',self.dog_count)
hi=Dog('hello','black')
hi.dog_count

1

In [116]:
hello=Dog('hello','black')
hello.dogCount()

총강아지는  2
내 강아지는  3


In [51]:
happy=Dog('happy','black')
happy.dogCount()


총 강아지는 2
내 강아지는 1


In [126]:
class Car: 
    car_count=0   #변수 생성 초기값 0으로 설정
    
    def __init__(self,name,gas,year):   #init:객체 생성시 자동 호출함수, name,gas,year는 필수 입력 속성 
        self.__name=name   #인스턴스 변수 비공개속성
        self.__gas=gas     #비공개속성 gas로 초기화
        self.__year=year    #비공개속성
        Car.car_count+=1  #
        
        
    def get_name(self):
        print('차종은 {}입니다.'.format(self.__name))
        
    def change_name(self, new_name):
        self.__name=new_name   #외부에서 변경은 안됨 
        
    def gas(self):
        if self.__gas<1000:
            print('소형')
        elif 1000<=self.__gas<=2000:
            print('중형')
        else:
            print('대형')
            
    @staticmethod       #정적 메서드인스턴스 속성, 메서드 접근 불가
    def carCount():
        print('총 등록된 자동차는',Car.car_count)   #__init__함수의 car_count 통해서 객체생성때마다 1증가

In [127]:
ford=Car('제네시스',2000,1984)

BMW=Car('x5',1000,2012)

BMW=Car('x6',1000,2012)

benz=Car('m',3000,2020)

kia=Car('k5',2400,2017)

BMW.carCount()

총 등록된 자동차는 5


In [120]:
ford.get_name() 

차종은 제네시스입니다.


In [181]:
ford.change_name('셀토스')
ford.get_name()

차종은 셀토스입니다.


In [182]:
Car.carCount()

총 등록된 자동차는 4


In [183]:
class Animal:
    def __init__(self):   #self 인스턴스 __init__ 함수
        self.hungry=0
    
    def eat(self):
        self.hungry-=10
        print('밥먹음',self.hungry)
    
    def walk(self):
        self.hungry+=10
        print('산책',self.hungry)
    

In [184]:
class Dog(Animal):
    def __init__(self):
        super().__init__()
    def sound(self):
        print('멍멍')

In [185]:
class Cat(Animal):
    def __init__(self):
        super().__init__()
    def sound(self):
        print('야옹')

In [186]:
dog=Dog()
dog.sound()

멍멍


In [188]:
dog.walk()

산책 20


In [191]:
cat=Cat()
cat.sound()

야옹


In [196]:
class Dog(Animal):
    def __init__(self):
        super().__init__()
    def sound(self):
        print('멍멍')
    def eat(self):
        super().eat()
        print('왈왈')

In [197]:
dog=Dog()
dog.eat()

밥먹음 -10
왈왈


In [198]:
class Dog(Animal):
    def __init__(self):
        super().__init__()
    def sound(self):
        print('멍멍')
    def eat(self):
        super().eat()
        print('왈왈')

In [204]:
for i in range(10,-10,-1):
    try:
        print(10/0)
    except  ZeroDivisionError as e:
        print("예외오류발생")


예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생


In [129]:
for i in range(10,-10,-1):
    try:
        print(i/0)
    except ZeroDivisionError as e:
        print('예외오류발생')

예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생
예외오류발생


In [130]:
x=[1,2,3]
try:
    a=x[4]
except Exception as e: 
    print('error:',e)


error: list index out of range


In [234]:
import pickle
try:
    file=open("data3.p",'rb')   #파일 읽기모드
    name=pickle.load(file)    #data.3파일에 name 읽기
    address=pickle.load(file)  #data.3파일에 address 읽기
    email=pickle.load(file)     #data.3파일에 email 읽기
    print(name,address,email) 
    
except FileNotFoundError as F:   #파일이 없을경우 실행
    file=open('data3.p','w')   #파일생성모드
    data=input("name,adress,email: ")
    file.write(data)   #데이터 내용 입력
finally:
    file.close() #파일 닫기

UnpicklingError: invalid load key, 'k'.

In [143]:
import pickle

try:
    
    with open("data3.pkl",'rb') as file:    #pickle 모듈을 이용하여 파일 불러오기
        name=pickle.load(file)  #name,address, eamil만 불러오기
        address=pickle.load(file)
        email=pickle.load(file)
        print(name,address,email)   
        
except FileNotFoundError as e:   
    print("file이 존재하지않습니다")
    name=input('이름을 입력해주세요')    
    address=input('주소를 입력해주세요')
    email=input('이메일 을 입력해주세요')

    with open('data3.pkl','wb') as file:   #pickle 모듈 이용하여 파일 저장하기
        pickle.dump(name,file)   #name을 저장
        pickle.dump(address,file)
        pickle.dump(email,file)
        print("파일이 생성되었습니다")

김 경기도 ㅇ


In [4]:
import pickle   #pickle 모듈 불러옴 모듈이란 함수나 변수 또는 클래스를 모아 놓은 파일이다.

try:
    with open('data5.pkl','rb') as file: #파일 읽기모드
        name=pickle.load(file)    #name, address, eamil 업로드
        address=pickle.load(file)
        email=pickle.load(file)
        print(name,address,email)
except FileNotFoundError as e:
    with open('data5.pkl','wb') as file: #파일 생성 모드
        
        print('파일이 존재하지 않습니다.')  
        name=input('이름을 입력하세요:')
        address=input('주소를 입력하세요: ')
        email=input('이메일을 입력하세요: ')
        
        pickle.dump(name,file)   #dump함수 이용하여 file에 데이터 저장
        pickle.dump(address,file)
        pickle.dump(email,file)
        print('파일이 생성되었습니다')
        

q d s


In [6]:
import pkcalcfolder.calc as calc   #패키지 pkcalcfolder 안에 모듈 이름 calc
print(calc.add(5,6))

import pkcalcfolder.calc as calc
print(calc.sub(5,6))

11
-1


In [6]:
from pkcalcfolder.calc import add,sub
print(add(5,6

11


In [7]:
import sys  #모듈과 패키지를 찾는 것 모듈은 변수, 함수, 클래스를  모아 둔 것 패키지는 모듈들을 모아둔 것
print(sys.path)

impr

['C:\\jupyter', 'C:\\ProgramData\\Anaconda3\\python38.zip', 'C:\\ProgramData\\Anaconda3\\DLLs', 'C:\\ProgramData\\Anaconda3\\lib', 'C:\\ProgramData\\Anaconda3', '', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\kimkwanghee\\.ipython']


In [10]:
import pkcalcfolder

In [11]:
print(add(7,3))

10


In [9]:
def add(a,b):
    return a+b
def sub(a,b):
    return a-b

if __name__=="__main__": #다른 모듈에서 import 할 시 함수만 가져옴 print문 제외 
    print(add(1,4))
    print(sub(1,4))

5
-3


In [16]:
import numpy as np   #!pip install pandas  넘파이 패키지 가져옴

In [17]:
import pandas as pd   

In [12]:
matrix_1=[[1,2],[3,4]]#2차원 리스트
matrix_2=[[5,6],[7,8]]

In [13]:
matrix_3=[]
for i in range(len(matrix_1)):   
    a=[]
    for j in range(len(matrix_1[i])):
        a.append(matrix_1[i][j]+matrix_2[i][j])
    matrix_3.append(a)
print(matrix_3)

[[6, 8], [10, 12]]


In [14]:
matrix_4=[]
for i in range(len(matrix_1)):
    a=[]
    for j in range(len(matrix_1[i])):
        a.append(matrix_1[i][j]+1)
    matrix_4.append(a)
print(matrix_4)

[[2, 3], [4, 5]]


In [55]:
def matrix_sum(mat1,mat2):
    for i in range(len(mat1)):
        for j in range(len(mat1[0])):
            mat1[i][j]+mat2[i][j]
    return 

In [19]:
matrix_sum=np.array(matrix_1)+np.array(matrix_2)

In [20]:
matrix_sum=np.array(matrix_1)+np.array(matrix_2)

In [21]:
print(matrix_sum)

[[ 6  8]
 [10 12]]


In [72]:
mat_one_plus=np.array(matrix_1)+1
mat_one_plus

array([[2, 3],
       [4, 5]])

In [23]:
mat_one_plus=np.array(matrix_1)+1
mat_one_plus

array([[2, 3],
       [4, 5]])

In [76]:
import time   #시간을 가지고오는 패키지


In [79]:
size=1000000
x=list(range(size))
y=list(range(size))

start_time=time.time()

z=[x[i]+x[i] for i in range(size)]
print(f"리스트 걸린 시간: {time.time()-start_time}")


리스트 걸린 시간: 0.3022022247314453


In [80]:
x=np.arange(size)
y=np.arange(size)

start_time=time.time()
z=x+y
print(f"넘파이 걸린 시간: {time.time()-start_time}")


넘파이 걸린 시간: 0.03391385078430176


In [26]:
x=np.uint(16)
print(x.dtype)  # uint 32비트 자료형 양수만


y=np.array([1,2,3,4])
print(y.dtype)



uint32


In [27]:
x=np.array([1,2])
print(x.shape)
      
      

(2,)


In [39]:


x=np.arange(24).reshape(2,3,4)
print(x)

x=np.arange(10)
print(x)


x=np.arange(10.0)
print(x)

x=np.arange(1,10,0.5)
print(x)

x=np.arange(10,1,-0.5)
print(x)

x=np.linspace(1,20,5,endpoint=False)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]
[ 1.   4.8  8.6 12.4 16.2]


In [93]:
x=np.arange(16).reshape(2,2,2,2)
x

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [53]:
x = np.array([[1,2],[3,4],[5,6]])
print(x,'\n')
print(x.reshape(2,3),'\n')

x=np.arange(9).reshape(3,3)
print(x,'\n')

x=np.arange(24).reshape(2,3,4)
print(x)

x=np.arange(16).reshape(2,2,2,2)
print(x)

x=np.array([[1,2],[3,4],[5,6]])
print(x.reshape(2,3))

x=np.arange(9).reshape(3,-1)
print(x)

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 3]
 [4 5 6]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [98]:
x=np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [54]:
x=np.float32([1,2,3,4])
np.array([1,2,3,4],dtype=np.float32)

In [104]:
np.int_([1,2,3,4])

array([1, 2, 3, 4])

In [105]:
np.int32(x)

array([1, 2, 3, 4])

In [106]:
x.dtype

dtype('float32')

In [ ]:
np.issubtype(ndarray.dtpye)
ndarray()