## 실습 1번

In [15]:
import pandas as pd
df=pd.read_csv('input3_out1.csv ')
df

1  2  0  -4
0   5  4  3   4
1   1  2 -1  -6
2   3  1  0   3
3   2  4  2  -4
4   4  1  2   9
5  -1  3  2  -7
6   4  3  3   5
7   0  2  6   6
8   2  2  1   0
9   1 -2 -2   4
10  0  1  3   3
11  1  1  3   5
12  0  1  4   5
13  2  3  3   1

In [16]:
import numpy as np
df_input=df.drop(['-4'],axis=1)
df_output=df['-4']

x=np.array(df_input.values.tolist())
y=np.array(df_output.values.tolist())

In [17]:
x

array([[ 5,  4,  3],
       [ 1,  2, -1],
       [ 3,  1,  0],
       [ 2,  4,  2],
       [ 4,  1,  2],
       [-1,  3,  2],
       [ 4,  3,  3],
       [ 0,  2,  6],
       [ 2,  2,  1],
       [ 1, -2, -2],
       [ 0,  1,  3],
       [ 1,  1,  3],
       [ 0,  1,  4],
       [ 2,  3,  3]])

In [18]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import optimizers

model = Sequential()
model.add(Dense(1, input_dim=3, activation='linear'))
sgd = optimizers.SGD(lr=0.01)
model.compile(optimizer=sgd ,loss='mse',metrics=['mse'])
model.fit(x,y, batch_size=2, epochs=10, shuffle=False)

Epoch 1/10
7/7 [==============================] - 0s 1ms/step - loss: 15.4262 - mse: 15.4262
Epoch 2/10
7/7 [==============================] - 0s 2ms/step - loss: 8.8039 - mse: 8.8039
Epoch 3/10
7/7 [==============================] - 0s 2ms/step - loss: 6.2664 - mse: 6.2664
Epoch 4/10
7/7 [==============================] - 0s 2ms/step - loss: 4.3809 - mse: 4.3809
Epoch 5/10
7/7 [==============================] - 0s 2ms/step - loss: 3.0695 - mse: 3.0695
Epoch 6/10
7/7 [==============================] - 0s 2ms/step - loss: 2.1562 - mse: 2.1562
Epoch 7/10
7/7 [==============================] - 0s 2ms/step - loss: 1.5178 - mse: 1.5178
Epoch 8/10
7/7 [==============================] - 0s 3ms/step - loss: 1.0705 - mse: 1.0705
Epoch 9/10
7/7 [==============================] - 0s 2ms/step - loss: 0.7565 - mse: 0.7565
Epoch 10/10
7/7 [==============================] - 0s 1ms/step - loss: 0.5357 - mse: 0.5357


## 실습 2번

In [19]:
import pandas as pd
df1=pd.read_csv('diabetes.csv')
x=df1.drop(['Outcome'],axis=1)
y=df1['Outcome']

In [20]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 
from tensorflow.keras import optimizers 

x_array=np.array(x.values.tolist())
y_array=np.array(y.values.tolist())

- x값을 8개씩 대입하므로 차원은 8, 시그모이드 함수 사용 
- Sequential의 뜻은 순차적, 연속적이라는 뜻입니다 층을 순차적으로 쌓는 것 
- 경사하강법=gradient descent는  함수 값이 낮아지는 방향으로 독립 변수 값을 변형시켜가면서 최종적으로는 최소 함수 값을 갖도록 하는 독립 변수 값을 찾는 방법이다.
- 옵티마이저=최적화 : 학습속도를 빠르고 안정적이게 하는 것으로 최적의 매개변수를 찾는 것 
- 확률적 경사하강법= sgd -> 옵티마이저의 종류 중 하나로서  (학습률=lr만큼 기울기를 변경시킴 ) -> 데이터를 다 보지 않고 일부만 보고 판단 
- 손실함수 : 실제 값과 예측값의 차이를 측정하는 함수 
- binary_crossentropy : 이진 분류에서 사용하는 손실함수 
- 모델 컴파일 : 모델을 훈련시키기 전에 훈련 과정에 필요한 매개변수를 정의하는 것 


In [23]:
model=Sequential()
model.add(Dense(1, input_dim=8, activation='sigmoid')) 
adagrad=optimizers.Adagrad(lr=0.01)
model.compile(optimizer=adagrad ,loss='binary_crossentropy',metrics=['binary_accuracy'])
model.fit(x_array,y_array, batch_size=5, epochs=300, shuffle=False)

Epoch 1/300
154/154 [==============================] - 1s 1ms/step - loss: 10.4198 - binary_accuracy: 0.5745
Epoch 2/300
154/154 [==============================] - 0s 1ms/step - loss: 7.9262 - binary_accuracy: 0.5593
Epoch 3/300
154/154 [==============================] - 0s 2ms/step - loss: 7.0137 - binary_accuracy: 0.5514
Epoch 4/300
154/154 [==============================] - 0s 1ms/step - loss: 6.4479 - binary_accuracy: 0.5280
Epoch 5/300
154/154 [==============================] - 0s 1ms/step - loss: 6.0732 - binary_accuracy: 0.5277
Epoch 6/300
154/154 [==============================] - 0s 1ms/step - loss: 5.7996 - binary_accuracy: 0.5172
Epoch 7/300
154/154 [==============================] - 0s 1ms/step - loss: 5.5820 - binary_accuracy: 0.5156A: 0s - loss: 5.5805 - binary_accuracy: 0.514
Epoch 8/300
154/154 [==============================] - 0s 1ms/step - loss: 5.4018 - binary_accuracy: 0.5109
Epoch 9/300
154/154 [==============================] - 0s 2ms/step - loss: 5.2478 - binary

154/154 [==============================] - 0s 1ms/step - loss: 1.7222 - binary_accuracy: 0.5728
Epoch 76/300
154/154 [==============================] - 0s 1ms/step - loss: 1.6957 - binary_accuracy: 0.5704
Epoch 77/300
154/154 [==============================] - 0s 1ms/step - loss: 1.6698 - binary_accuracy: 0.5709
Epoch 78/300
154/154 [==============================] - 0s 1ms/step - loss: 1.6442 - binary_accuracy: 0.5717
Epoch 79/300
154/154 [==============================] - 0s 1ms/step - loss: 1.6191 - binary_accuracy: 0.5731
Epoch 80/300
154/154 [==============================] - 0s 1ms/step - loss: 1.5944 - binary_accuracy: 0.5745
Epoch 81/300
154/154 [==============================] - 0s 1ms/step - loss: 1.5701 - binary_accuracy: 0.5745
Epoch 82/300
154/154 [==============================] - 0s 1ms/step - loss: 1.5462 - binary_accuracy: 0.5688
Epoch 83/300
154/154 [==============================] - 0s 1ms/step - loss: 1.5228 - binary_accuracy: 0.5677
Epoch 84/300
154/154 [==========

154/154 [==============================] - 0s 1ms/step - loss: 0.7509 - binary_accuracy: 0.6261
Epoch 150/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7472 - binary_accuracy: 0.6261
Epoch 151/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7437 - binary_accuracy: 0.6239
Epoch 152/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7403 - binary_accuracy: 0.6247
Epoch 153/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7370 - binary_accuracy: 0.6254
Epoch 154/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7339 - binary_accuracy: 0.6239
Epoch 155/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7308 - binary_accuracy: 0.6244
Epoch 156/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7278 - binary_accuracy: 0.6211
Epoch 157/300
154/154 [==============================] - 0s 1ms/step - loss: 0.7249 - binary_accuracy: 0.6211
Epoch 158/300
154/154 [=

154/154 [==============================] - 0s 1ms/step - loss: 0.6447 - binary_accuracy: 0.6501
Epoch 224/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6442 - binary_accuracy: 0.6501
Epoch 225/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6438 - binary_accuracy: 0.6498
Epoch 226/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6433 - binary_accuracy: 0.6498
Epoch 227/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6429 - binary_accuracy: 0.6493
Epoch 228/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6425 - binary_accuracy: 0.6501
Epoch 229/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6421 - binary_accuracy: 0.6501
Epoch 230/300
154/154 [==============================] - 0s 2ms/step - loss: 0.6417 - binary_accuracy: 0.6501
Epoch 231/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6413 - binary_accuracy: 0.6498
Epoch 232/300
154/154 [=

154/154 [==============================] - 0s 1ms/step - loss: 0.6265 - binary_accuracy: 0.6633
Epoch 298/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6264 - binary_accuracy: 0.6633
Epoch 299/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6262 - binary_accuracy: 0.6633
Epoch 300/300
154/154 [==============================] - 0s 1ms/step - loss: 0.6261 - binary_accuracy: 0.6641


In [6]:
x_array[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [7]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
model.predict([[1,85, 66,29,0,26.6,0.351,80]])

array([[0.]], dtype=float32)

## 실습 3번

In [24]:
x = [2,  4, 6, 8, 10, 12, 14, 16, 18, 20 ]
y = [0,  0, 0, 0,  0,   0,  1,   1,   1,  1]

x_train=[]
target=[]
for i in x:
    x_train.append([i])
for j in y:
    target.append([j])

In [32]:
from tensorflow import keras
import numpy as np

vocab_size=21
model=keras.Sequential()
model.add(keras.layers.Embedding(vocab_size,16,input_shape=(None,)))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(10,activation='relu'))
model.add(keras.layers.Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 16)          336       
_________________________________________________________________
global_average_pooling1d_2 ( (None, 16)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                170       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 11        
Total params: 517
Trainable params: 517
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.compile(optimizer='adam', loss='binary_crossentropy',
             metrics=['accuracy'])

In [34]:
train_data=np.array(x_train,dtype=int)
target_data=np.array(y_train,dtype=int)

In [36]:
train_data[0]

array([2])

In [39]:
model.fit(train_data,target_data,
            epochs=8,
            batch_size=512,
            verbose=1)
output_pred=model.predict_classes(train_data)

Epoch 1/8
1/1 [==============================] - 2s 2s/step - loss: 0.6968 - accuracy: 0.4000
Epoch 2/8
1/1 [==============================] - 0s 13ms/step - loss: 0.6941 - accuracy: 0.4000
Epoch 3/8
1/1 [==============================] - 0s 20ms/step - loss: 0.6916 - accuracy: 0.5000
Epoch 4/8
1/1 [==============================] - 0s 12ms/step - loss: 0.6892 - accuracy: 0.6000
Epoch 5/8
1/1 [==============================] - 0s 7ms/step - loss: 0.6869 - accuracy: 0.7000
Epoch 6/8
1/1 [==============================] - 0s 9ms/step - loss: 0.6848 - accuracy: 0.7000
Epoch 7/8
1/1 [==============================] - 0s 12ms/step - loss: 0.6827 - accuracy: 0.8000
Epoch 8/8
1/1 [==============================] - 0s 12ms/step - loss: 0.6807 - accuracy: 0.8000


In [40]:
output_pred

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [41]:
test_data

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])