In [1]:
import tensorflow as tf

tf.executing_eagerly() #2,0은 기본적으로 가지고 있음  그래서 사용안해도 됨 

True

In [2]:
x=[[2.]]  
m=tf.matmul(x,x)
print('hello, {}'.format(m))

hello, [[4.]]


### 브로드캐스팅

In [4]:
a=tf.constant([[1,2],[3,4]])   # 상수 값을 사용하기 위해 constant 함수 사용 
tf.add(a,1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [5]:
c=tf.constant([[1,1]])
tf.add(a,c)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [7]:
print(a*c)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### 텐서플로우  -> 넘파이로 변경하여 계산

In [9]:
import numpy as np
b=np.multiply(a,c)   #텐서플로우를 넘파이로 바로 변경하여 계산
print(b)  

b=np.multiply(a,c)


[[1 2]
 [3 4]]


In [5]:
a=tf.convert_to_tensor(10)

a.numpy()

10

### 동적인 제어 흐름 

In [10]:
def fizzbuzz(max_num):
#     counter=tf.constant(0)
    max_num=tf.convert_to_tensor(max_num) #텐서로 변환 
    for num in range(1, max_num.numpy()+1):  #텐서를 넘파이로 변환 
        num=tf.constant(num)   
        if int(num%3)==0 and int(num%5)==0:
            print('FizzBuzz')
        elif int(num%3)==0:
            print('Fizz')
        elif int(num%5)==0:
            print('Buzz')
        else:
            print(num.numpy())
        counter+=1

In [20]:

max_num=tf.convert_to_tensor(max_num)
max_num.numpy()

15

fizzbuzz(15)

### 그래디언트 계산

In [21]:
w=tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss=w*w
grad=tape.gradient(loss,w)   #loss를 w변수를 기준으로 미분 ->   즉 w^2 -> 2w=2*1=2
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


### 모델 훈련

In [22]:
(mnist_images, mnist_labels),_=tf.keras.datasets.mnist.load_data()
dataset=tf.data.Dataset.from_tensor_slices(
    (tf.cast(mnist_images[...,tf.newaxis]/255,tf.float32),
    tf.cast(mnist_labels,tf.int64)))
dataset=dataset.shuffle(1000).batch(32)

In [25]:
mnist_images.shape

(60000, 28, 28)

In [28]:
a=mnist_images[...,tf.newaxis] #새로운 축 생성 방법 1 ...은 알아서 생성 

In [29]:
a.shape   #새로운 열이 생김

(60000, 28, 28, 1)

In [34]:
mnist_images[tf.newaxis,:].shape #새로운 축 생성 방법 2

(1, 60000, 28, 28)

In [36]:
mnist_images[:,:,tf.newaxis,:].shape 

(60000, 28, 1, 28)

In [37]:
x=tf.Variable(10.)
checkpoint=tf.train.Checkpoint(x=x)
x.assign(2.)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [38]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [43]:
checkpoint_path='./ckpt/'
checkpoint.save(checkpoint_path)

'./ckpt/-3'

### 체크포인트 복구 

In [44]:
checkpoint.restore(tf.train.latest_checkpoint(checkpoint_path))

In [45]:
m=tf.keras.metrics.Mean('loss')    #m에 대입한 총 숫자의 평균 계산

In [46]:
m(0)   

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [47]:
m(5)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [48]:
m([8,9])

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>

In [49]:
c=tf.constant([[4.0,5.0],[10.0,1.0]])
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [50]:
tf.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0], dtype=int64)>

In [51]:
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

## 텐서-형상 정보
- 텐서는 형상이 있습니다. 사용되는 일부 용어는 다음과 같습니다.

- 형상: 텐서의 각 차원의 길이(요소의 수)
- 순위: 텐서 차원의 수입니다. 스칼라는 순위가 0이고 벡터의 순위는 1이며 행렬의 순위는 2입니다.
- 축 또는 차원: 텐서의 특정 차원
- 크기: 텐서의 총 항목 수, 곱 형상 벡터
- 참고: "2차원 텐서"에 대한 참조가 있을 수 있지만, 순위-2 텐서는 일반적으로 2D 공간을 설명하지 않습니다.

텐서 및 tf.TensorShape 객체에는 다음에 액세스하기 위한 편리한 속성이 있습니다.

In [52]:
rank_4=tf.zeros([3,2,4,5])   # 차원 4, batch 3, width 2, height 4, features 5

In [54]:
rank_4

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [56]:
rank_4.dtype

tf.float32

In [58]:
rank_4.shape[0]

3

In [59]:
rank_4.ndim

4

In [60]:
tf.size(rank_4).numpy() # 3*2*4*5=120

120

In [61]:
rank_3

NameError: name 'rank_3' is not defined

In [63]:
rank_3 = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
rank_3[:,:,4]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  9],
       [14, 19],
       [24, 29]])>

In [64]:
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
print(var_x.shape)

(3, 1)


In [65]:
var_x

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [68]:
var_x.shape.as_list()

[3, 1]

In [70]:
reshaped=tf.reshape(var_x,[1,3])
reshaped

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [75]:
rank_3.shape


TensorShape([3, 2, 5])

In [76]:
tf.reshape(rank_3,[5,6])

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])>

In [77]:
try:
    tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
    print(f"{type(e).__name__}: {e}")

NameError: name 'rank_3_tensor' is not defined


In [78]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")   #데이터 위치, 값, 모양

# We can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
