In [1]:
import tensorflow as tf
import numpy as np

In [3]:
rank_0=tf.constant(4)  #축이 없음 =randk가 0
rank_0

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
rank_1=tf.constant([2.0,3.0,4.0])  #축이 있음 -> rank는 1
rank_1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [10]:
rank_2=tf.constant([[1,2],[3,4],[5,6]],dtype=tf.float16) # rank는 2
rank_2    

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [11]:
rank_3=tf.constant([[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]])
rank_3

<tf.Tensor: shape=(1, 3, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])>

In [19]:
rank_4=tf.constant(
    [[[0,1,2,3],
    [5,6,1,1]],
     
    [[1,2,3,4],
    [1,1,1,1]],
     
    [[3,4,5,6],
    [6,6,6,6]]])
rank_4

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[0, 1, 2, 3],
        [5, 6, 1, 1]],

       [[1, 2, 3, 4],
        [1, 1, 1, 1]],

       [[3, 4, 5, 6],
        [6, 6, 6, 6]]])>

### 비정형텐서

In [21]:
digits = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
digits

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>

 ### 텐서에 대한 기본수학 

In [22]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 

