## 특징공학
* 범주형 -> 수치형으로 변환하는 작업은 인코딩 작업과 같음
* ex) 성별 남녀 -> 1과 2로 표현 -> 01,10으로 표현

### 범주형 데이터를 수치형 데이터로 변환

In [35]:
import sys
sys.maxsize

9223372036854775807

In [36]:
import sys

data=[
    {'price':120000000000 ,'rooms':3,'location':'잠실동'},
    {'price':700000000000,'rooms':4,'location':'천호동'},
    {'price':80000000000 ,'rooms':4,'location':'신천동'},
    {'price':90000000000 ,'rooms':2,'location':'천호동'}
]


In [37]:
type(data)

list

In [38]:
import numpy as np

In [39]:
from sklearn.feature_extraction import DictVectorizer   #딕셔너리 데이터를 벡터로 만드는 함수  

In [41]:
dv=DictVectorizer(sparse=False, dtype=np.int64)   #int64로 2^64까지 숫자저장가능 
dv.fit_transform(data)

array([[           0,            1,            0, 120000000000,
                   3],
       [           0,            0,            1, 700000000000,
                   4],
       [           1,            0,            0,  80000000000,
                   4],
       [           0,            0,            1,  90000000000,
                   2]], dtype=int64)

In [31]:
dv.get_feature_names()  #리스트안의 각각의 딕셔너리에서 키=value값(범주형데이터)으로 출력 

['location=신천동', 'location=잠실동', 'location=천호동', 'price', 'rooms']

In [43]:
dv=DictVectorizer(sparse=True,dtype=np.int64)  #희소행렬로 변환 
dv.fit_transform(data)   #데이터를 변형시키는 작업

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

### 텍스트 데이터 -> 수치형 데이터로 변환

In [53]:
text=[
    'mobile phone',
    'battlegrounds mobile phone',
    'phone game'
]

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
cv=CountVectorizer()
x=cv.fit_transform(text)
x

<3x4 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [58]:
import pandas as pd
pd.DataFrame(x.toarray(),columns=cv.get_feature_names())

battlegrounds  game  mobile  phone
0              0     0       1      1
1              1     0       1      1
2              0     1       0      1

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv=TfidfVectorizer()
x=tv.fit_transform(text)
x

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [62]:
pd.DataFrame(x.toarray(),columns=tv.get_feature_names())
#3개의 문장에서 각 단어의 비중 -> 가중치 계산 = TF*IDF

battlegrounds      game    mobile     phone
0       0.000000  0.000000  0.789807  0.613356
1       0.720333  0.000000  0.547832  0.425441
2       0.000000  0.861037  0.000000  0.508542

### 누락 데이터 대체 

In [70]:
x=np.array([[np.nan,0,3],[3,7,9],[3,5,2],[4,np.nan,6],[8,8,1]])
y=np.array([14,16,-1,8,-5])

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

x2=imputer.fit_transform(x)
x2

array([[4.5, 0. , 3. ],
       [3. , 7. , 9. ],
       [3. , 5. , 2. ],
       [4. , 5. , 6. ],
       [8. , 8. , 1. ]])

In [73]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x2,y)
y_pred=model.predict(x2)
y_pred

array([13.14869292, 14.3784627 , -1.15539732, 10.96606197, -5.33782027])