In [1]:
import tensorflow

In [3]:
tensorflow.__version__

'2.4.0'

In [12]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[1,1,1],[1,1,1],[1,1,1]]
a+b

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [13]:
# c=[[0]*3 for i in range(3)]
# c

In [17]:
d=[[0]*3 for i in range(0,3)]
for i in range(0,3):
    for j in range(0,3):
        d[i][j]=a[i][j]+b[i][j]

In [19]:
d

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [41]:
import numpy as np

In [40]:
np.array(a)+ np.array(b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## 과제 1

In [23]:
m=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [44]:
m[1,2]

7

In [28]:
m[2,-1]

14

In [29]:
m[1,1:3]

array([6, 7])

In [30]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
m[1:3,2]

array([ 7, 12])

In [39]:
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [42]:
np.save('my_array',m)

In [43]:
np.save('my_array.csv',m)

### 파이썬 객체

In [46]:
c1=999
a1=c1

In [47]:
id(c1)

2138752575216

In [48]:
id(a1)

2138752575216

In [ ]:
a1=