In [1]:
import pandas as pd
breast_cancer=pd.read_csv('breast-cancer-wisconsin.data')

In [5]:
breast_cancer.columns=['id_number','clumb_thickness','unif_cell_size','unif_cell_shape'
                      ,'marg_adesion','single_epith_cell_size','bare_nuciei','bland_chromatin'
                      ,'normal_nuclioli','mitoses','class']

In [6]:
breast_cancer.info()   #데이터에 대한 전반적인 정보  컬럼 이름, 결측치 여부 , 데이터 타입 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   id_number               698 non-null    int64 
 1   clumb_thickness         698 non-null    int64 
 2   unif_cell_size          698 non-null    int64 
 3   unif_cell_shape         698 non-null    int64 
 4   marg_adesion            698 non-null    int64 
 5   single_epith_cell_size  698 non-null    int64 
 6   bare_nuciei             698 non-null    object
 7   bland_chromatin         698 non-null    int64 
 8   normal_nuclioli         698 non-null    int64 
 9   mitoses                 698 non-null    int64 
 10  class                   698 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.1+ KB


In [10]:
breast_cancer.isnull().sum()

id_number                 0
clumb_thickness           0
unif_cell_size            0
unif_cell_shape           0
marg_adesion              0
single_epith_cell_size    0
bare_nuciei               0
bland_chromatin           0
normal_nuclioli           0
mitoses                   0
class                     0
dtype: int64

In [23]:
breast_cancer

id_number  clumb_thickness  unif_cell_size  unif_cell_shape  \
0      1002945                5               4                4   
1      1015425                3               1                1   
2      1016277                6               8                8   
3      1017023                4               1                1   
4      1017122                8              10               10   
..         ...              ...             ...              ...   
693     776715                3               1                1   
694     841769                2               1                1   
695     888820                5              10               10   
696     897471                4               8                6   
697     897471                4               8                8   

     marg_adesion  single_epith_cell_size bare_nuciei  bland_chromatin  \
0               5                       7          10                3   
1               1                       2           2                3   
2               1                       3           4                3   
3               3                       2           1                3   
4               8                       7          10                9   
..            ...                     ...         ...              ...   
693             1                       3           2                1   
694             1                       2           1                1   
695             3                       7           3                8   
696             4                       3           4               10   
697             5                       4           5               10   

     normal_nuclioli  mitoses  class  
0                  2        1      2  
1                  1        1      2  
2                  7        1      2  
3                  1        1      2  
4                  7        1      4  
..               ...      ...    ...  
693                1        1      2  
694                1        1      2  
695               10        2      4  
696                6        1      4  
697                4        1      4  

[698 rows x 11 columns]

In [27]:
breast_cancer['bare_nuciei'].min()

'1'

In [28]:
import numpy as np

# breast_cancer['bare_nuciei']=breast_cancer['bare_nuciei'].replace('?',np.nan)

In [29]:
breast_cancer['bare_nuciei']=breast_cancer['bare_nuciei'].replace('?',np.nan)

In [31]:
breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   id_number               698 non-null    int64 
 1   clumb_thickness         698 non-null    int64 
 2   unif_cell_size          698 non-null    int64 
 3   unif_cell_shape         698 non-null    int64 
 4   marg_adesion            698 non-null    int64 
 5   single_epith_cell_size  698 non-null    int64 
 6   bare_nuciei             682 non-null    object
 7   bland_chromatin         698 non-null    int64 
 8   normal_nuclioli         698 non-null    int64 
 9   mitoses                 698 non-null    int64 
 10  class                   698 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.1+ KB


In [33]:
breast_cancer['bare_nuciei']=breast_cancer['bare_nuciei'].fillna(breast_cancer['bare_nuciei'].value_counts().index[0])

In [40]:
breast_cancer['cancer_ind']=0

In [31]:
breast_cancer['cancer_ind']=0

In [37]:
breast_cancer['bare_nuciei'].tolist()

['10',
 '2',
 '4',
 '1',
 '10',
 '10',
 '1',
 '1',
 '1',
 '1',
 '1',
 '3',
 '3',
 '9',
 '1',
 '1',
 '1',
 '10',
 '1',
 '10',
 '7',
 '1',
 '1',
 '1',
 '7',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '5',
 '1',
 '1',
 '1',
 '1',
 '1',
 '10',
 '7',
 '1',
 '3',
 '10',
 '1',
 '1',
 '1',
 '9',
 '1',
 '1',
 '8',
 '3',
 '4',
 '5',
 '8',
 '8',
 '5',
 '6',
 '1',
 '10',
 '2',
 '3',
 '2',
 '8',
 '2',
 '1',
 '2',
 '1',
 '10',
 '9',
 '1',
 '1',
 '2',
 '1',
 '10',
 '4',
 '2',
 '1',
 '1',
 '3',
 '1',
 '1',
 '1',
 '1',
 '2',
 '9',
 '4',
 '8',
 '10',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '6',
 '10',
 '5',
 '5',
 '1',
 '3',
 '1',
 '3',
 '10',
 '10',
 '1',
 '9',
 '2',
 '9',
 '10',
 '8',
 '3',
 '5',
 '2',
 '10',
 '3',
 '2',
 '1',
 '2',
 '10',
 '10',
 '7',
 '1',
 '10',
 '1',
 '10',
 '1',
 '1',
 '1',
 '10',
 '1',
 '1',
 '2',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '5',
 '5',
 '1',
 '1',
 '8',
 '2',
 '1',
 '10',
 '1',
 '10',
 '5',
 '3',
 '1',
 '10',
 '1',
 '1',
 '1',
 '10',
 '10',
 '1',
 '1',
 '

In [41]:
# breast_cancer.loc[breast_cancer['class']==4,'cancer_ind']=1

In [42]:
breast_cancer.loc[breast_cancer['class']==4,'cancer_ind']=1

In [50]:
x=breast_cancer.drop(['id_number','class','cancer_ind'],axis=1)
y=breast_cancer['cancer_ind']

In [51]:
breast_cancer

id_number  clumb_thickness  unif_cell_size  unif_cell_shape  \
0      1002945                5               4                4   
1      1015425                3               1                1   
2      1016277                6               8                8   
3      1017023                4               1                1   
4      1017122                8              10               10   
..         ...              ...             ...              ...   
693     776715                3               1                1   
694     841769                2               1                1   
695     888820                5              10               10   
696     897471                4               8                6   
697     897471                4               8                8   

     marg_adesion  single_epith_cell_size bare_nuciei  bland_chromatin  \
0               5                       7          10                3   
1               1                       2           2                3   
2               1                       3           4                3   
3               3                       2           1                3   
4               8                       7          10                9   
..            ...                     ...         ...              ...   
693             1                       3           2                1   
694             1                       2           1                1   
695             3                       7           3                8   
696             4                       3           4               10   
697             5                       4           5               10   

     normal_nuclioli  mitoses  class  cancer_ind  
0                  2        1      2           0  
1                  1        1      2           0  
2                  7        1      2           0  
3                  1        1      2           0  
4                  7        1      4           1  
..               ...      ...    ...         ...  
693                1        1      2           0  
694                1        1      2           0  
695               10        2      4           1  
696                6        1      4           1  
697                4        1      4           1  

[698 rows x 12 columns]

In [56]:
x

clumb_thickness  unif_cell_size  unif_cell_shape  marg_adesion  \
0                  5               4                4             5   
1                  3               1                1             1   
2                  6               8                8             1   
3                  4               1                1             3   
4                  8              10               10             8   
..               ...             ...              ...           ...   
693                3               1                1             1   
694                2               1                1             1   
695                5              10               10             3   
696                4               8                6             4   
697                4               8                8             5   

     single_epith_cell_size bare_nuciei  bland_chromatin  normal_nuclioli  \
0                         7          10                3                2   
1                         2           2                3                1   
2                         3           4                3                7   
3                         2           1                3                1   
4                         7          10                9                7   
..                      ...         ...              ...              ...   
693                       3           2                1                1   
694                       2           1                1                1   
695                       7           3                8               10   
696                       3           4               10                6   
697                       4           5               10                4   

     mitoses  
0          1  
1          1  
2          1  
3          1  
4          1  
..       ...  
693        1  
694        1  
695        2  
696        1  
697        1  

[698 rows x 9 columns]

In [57]:
y

0      0
1      0
2      0
3      0
4      1
      ..
693    0
694    0
695    1
696    1
697    1
Name: cancer_ind, Length: 698, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split   #
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [53]:
from sklearn.preprocessing import StandardScaler   # 사이킷런에는 표준화를 위한 StandardScaler 변환기
scaler=StandardScaler()

In [54]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)  #정규화 한다고 항상 성능이 좋아지는 것은 아님 

In [59]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)  #k값을 1로 설정 
knn.fit(x_train_scaled,y_train)  # 정규화된 테스트 데이터를 knn알고리즘에 훈련

KNeighborsClassifier(n_neighbors=1)

In [60]:
from sklearn.metrics import accuracy_score,confusion_matrix, roc_auc_score,roc_curve
y_pred=knn.predict(x_test_scaled)  # 훈련 데이터로 구축된 knn 알고리즘을 정규화된 테스트 데이터로 예측 


In [119]:
confusion_matrix(y_test,y_pred)  #오차 행렬-> y가 0과 1로 이루어졌기 때문에 오차행렬 사용 y_pred: 얘측값 y_test: 실제값 

array([[140,   2],
       [  6,  62]], dtype=int64)

In [62]:
accuracy_score(y_test,y_pred)   # 혼동행렬에서 (140+62)/(140+2+6+62)의 값 

0.9619047619047619

In [120]:
roc_auc_score(y_test,y_pred)   #roc 커브의 아래쪽 면적을 tpr이 y축 fpr이 x축 
#1에 가까울수록 클래스를 분류하는 성능이 뛰어남 
#즉 무조건 0이라고 예측하여 정확도를 높이는 것에 대한 가능성을 줄여줌 


0.9488400994200497

In [65]:
from sklearn.model_selection import GridSearchCV   #모델에 여러개의 파라미터를 만들어 대입시켜주는 함수 
grid_search=GridSearchCV(knn, {'n_neighbors':[1,2,3,4,5]},n_jobs=-1, cv=7, scoring='roc_auc')  
#estimator=knn, 변수값은 딕셔너리 형태로 대입, n_jobs는 사용 컴퓨터 코어 개수 지정 -1값은 모든 코어 사용, cv=교차검증 변수 개수 
grid_search.fit(x_train_scaled,y_train)    #scoring에 따라 정확도 달라짐 

GridSearchCV(cv=7, estimator=KNeighborsClassifier(n_neighbors=1), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5]}, scoring='roc_auc')

In [122]:
grid_search.best_params_

{'n_neighbors': 5}

In [68]:
knn_best=grid_search.best_estimator_

In [67]:
y_pred=grid_search.predict(x_test_scaled)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [69]:
y_pred=knn_best.predict(x_test_scaled)

y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [71]:
accuracy_score(y_test,y_pred)

0.9761904761904762

In [72]:
confusion_matrix(y_test,y_pred)

array([[141,   1],
       [  4,  64]], dtype=int64)

In [73]:
roc_auc_score(y_test,y_pred)

0.9670671085335543